"""create tax_rule_sets and tax_rules tables

Revision ID: 061b32a9e2b2
Revises: 0d7c53f0b3a0
Create Date: 2026-09-10 11:37:37.966339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '061b32a9e2b2'
down_revision: Union[str, Sequence[str], None] = '0d7c53f0b3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rule_sets',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.String(length=50), nullable=True),
    sa.Column('effective_to', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rule_set_id')
    )
    op.create_index(op.f('ix_tax_rule_sets_rule_set_id'), 'tax_rule_sets', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_tax_rule_sets_tax_year'), 'tax_rule_sets', ['tax_year'], unique=True)
    op.create_table('tax_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=True),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.String(length=50), nullable=True),
    sa.Column('effective_to', sa.String(length=50), nullable=True),
    sa.Column('legal_document', sa.String(length=255), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('clause', sa.String(length=100), nullable=True),
    sa.Column('point', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['tax_rule_sets.rule_set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_tax_rules_rule_code'), 'tax_rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_tax_rules_rule_id'), 'tax_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_tax_rules_rule_set_id'), 'tax_rules', ['rule_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_rules_rule_set_id'), table_name='tax_rules')
    op.drop_index(op.f('ix_tax_rules_rule_id'), table_name='tax_rules')
    op.drop_index(op.f('ix_tax_rules_rule_code'), table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_tax_rule_sets_tax_year'), table_name='tax_rule_sets')
    op.drop_index(op.f('ix_tax_rule_sets_rule_set_id'), table_name='tax_rule_sets')
    op.drop_table('tax_rule_sets')
    # ### end Alembic commands ###
