"""add_ai_extractions_and_system_configs

Revision ID: 4b7e28a09f3a
Revises: 4fa0af19972a
Create Date: 2026-09-16 22:31:20.803257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b7e28a09f3a'
down_revision: Union[str, Sequence[str], None] = '4fa0af19972a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('applied_threshold', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_passed_threshold', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_admin_id'), 'ai_extractions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_document_id'), 'ai_extractions', ['document_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_index(op.f('ix_system_configs_admin_id'), 'system_configs', ['admin_id'], unique=False)
    op.create_table('ai_extractions_value',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('user_corrected_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['ai_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_value_extraction_id'), 'ai_extractions_value', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_url_validation_rules_created_by'), 'url_validation_rules', ['created_by'], unique=False)
    op.create_index(op.f('ix_url_validation_rules_updated_by'), 'url_validation_rules', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_validation_rules_updated_by'), table_name='url_validation_rules')
    op.drop_index(op.f('ix_url_validation_rules_created_by'), table_name='url_validation_rules')
    op.drop_index(op.f('ix_ai_extractions_value_extraction_id'), table_name='ai_extractions_value')
    op.drop_table('ai_extractions_value')
    op.drop_index(op.f('ix_system_configs_admin_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_ai_extractions_document_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_admin_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    # ### end Alembic commands ###
