"""refactor_url_rules_to_domain_only

Revision ID: 4fa0af19972a
Revises: 96cdba01554b
Create Date: 2026-09-14 23:22:07.493949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4fa0af19972a'
down_revision: Union[str, Sequence[str], None] = '96cdba01554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Thêm cột domain (cho phép null tạm thời)
    op.add_column('url_validation_rules', sa.Column('domain', sa.String(length=255), nullable=True))
    # 2. Sao chép dữ liệu từ cột pattern sang domain nếu có dữ liệu cũ
    op.execute("UPDATE url_validation_rules SET domain = pattern WHERE domain IS NULL")
    # 3. Đổi sang nullable=False
    op.alter_column('url_validation_rules', 'domain', nullable=False)
    # 4. Xóa các cột cũ pattern và rule_type
    op.drop_column('url_validation_rules', 'pattern')
    op.drop_column('url_validation_rules', 'rule_type')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_validation_rules', sa.Column('rule_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('url_validation_rules', sa.Column('pattern', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('url_validation_rules', 'domain')
    # ### end Alembic commands ###
