"""remove_admin_id_from_ai_extractions

Revision ID: 6c92261815cc
Revises: 4b7e28a09f3a
Create Date: 2026-09-16 23:02:06.539834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6c92261815cc'
down_revision: Union[str, Sequence[str], None] = '4b7e28a09f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_extractions_admin_id'), table_name='ai_extractions')
    op.drop_column('ai_extractions', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_extractions', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_ai_extractions_admin_id'), 'ai_extractions', ['admin_id'], unique=False)
    # ### end Alembic commands ###
