"""add_soft_delete_to_url_validation_rules

Revision ID: 96cdba01554b
Revises: 1ac7a72d33eb
Create Date: 2026-09-14 21:59:12.185824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '96cdba01554b'
down_revision: Union[str, Sequence[str], None] = '1ac7a72d33eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_validation_rules', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('url_validation_rules', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_url_validation_rules_is_deleted'), 'url_validation_rules', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_validation_rules_is_deleted'), table_name='url_validation_rules')
    op.drop_column('url_validation_rules', 'deleted_at')
    op.drop_column('url_validation_rules', 'is_deleted')
    # ### end Alembic commands ###
