"""update_dependent_rules_fk_to_tax_rules

Revision ID: bec9171d3258
Revises: fc8675894b50
Create Date: 2026-09-11 21:56:38.483215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bec9171d3258'
down_revision: Union[str, Sequence[str], None] = 'fc8675894b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent_rules', 'rule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_dependent_rules_rule_set_id'), table_name='dependent_rules')
    op.drop_constraint(op.f('dependent_rules_rule_set_id_fkey'), 'dependent_rules', type_='foreignkey')
    op.drop_constraint(op.f('dependent_rules_rule_id_fkey'), 'dependent_rules', type_='foreignkey')
    op.create_foreign_key(None, 'dependent_rules', 'tax_rules', ['rule_id'], ['rule_id'], ondelete='CASCADE')
    op.drop_column('dependent_rules', 'rule_set_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependent_rules', sa.Column('rule_set_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dependent_rules', type_='foreignkey')
    op.create_foreign_key(op.f('dependent_rules_rule_id_fkey'), 'dependent_rules', 'tax_rules', ['rule_id'], ['rule_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('dependent_rules_rule_set_id_fkey'), 'dependent_rules', 'tax_rule_sets', ['rule_set_id'], ['rule_set_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_dependent_rules_rule_set_id'), 'dependent_rules', ['rule_set_id'], unique=False)
    op.alter_column('dependent_rules', 'rule_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
