"""create_dependent_rules_table

Revision ID: fc8675894b50
Revises: 7b6fbcdd7cb2
Create Date: 2026-09-10 19:56:32.490916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'fc8675894b50'
down_revision: Union[str, Sequence[str], None] = '7b6fbcdd7cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('dependent_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('max_monthly_income', sa.Float(), nullable=True),
    sa.Column('is_studying', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['tax_rules.rule_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['tax_rule_sets.rule_set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependent_rules_dependent_type'), 'dependent_rules', ['dependent_type'], unique=False)
    op.create_index(op.f('ix_dependent_rules_id'), 'dependent_rules', ['id'], unique=False)
    op.create_index(op.f('ix_dependent_rules_rule_id'), 'dependent_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_dependent_rules_rule_set_id'), 'dependent_rules', ['rule_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependent_rules_rule_set_id'), table_name='dependent_rules')
    op.drop_index(op.f('ix_dependent_rules_rule_id'), table_name='dependent_rules')
    op.drop_index(op.f('ix_dependent_rules_id'), table_name='dependent_rules')
    op.drop_index(op.f('ix_dependent_rules_dependent_type'), table_name='dependent_rules')
    op.drop_table('dependent_rules')
    # ### end Alembic commands ###
